### ISSUE TITLE
Demo's broken

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [englishextra/img-lightbox#7]
https://codepen.io/englishextra/full/YLQxRp

**Comment by englishextra** [comment]
@alxndr-w Could you  please explain in greater detail what exactly fails?

If I click on the image with a cat, the lightbox launches successfully. Maybe I missed something.
![2021-03-15_144946](https://user-images.githubusercontent.com/537127/111149583-1a72f300-859e-11eb-97ac-83688b389c67.jpg)

Maybe you didn't unblock something in Brave browser or whatever browser you manipulate.

**Comment by AWqxKAWERbXo** [comment]
![image](https://user-images.githubusercontent.com/3855487/111446286-870c0000-870c-11eb-8383-ef57f4a5e669.png)

I guess you're right, codepen.io blocks js if you don't run their ads. 

![image](https://user-images.githubusercontent.com/3855487/111446408-a9058280-870c-11eb-8001-adefe9f35daf.png)

Sorry, a false alarm.
